# Generated by Django 2.2.9 on 2020-01-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='info2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='info3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
