# Generated by Django 2.2.9 on 2020-01-11 15:47

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
