# Generated by Django 2.2.9 on 2020-01-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0003_genericpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='package',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
