# Generated by Django 2.2.9 on 2020-01-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0004_genericpage_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericpage',
            options={'verbose_name': 'Спецификация Товара', 'verbose_name_plural': 'Спецификация Товара'},
        ),
        migrations.RenameField(
            model_name='genericpage',
            old_name='content',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='genericpage',
            name='name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
