# Generated by Django 2.2.9 on 2020-01-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0005_auto_20200112_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='photo',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='name',
        ),
        migrations.AddField(
            model_name='genericpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='package',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
