# Generated by Django 2.2.9 on 2020-01-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0006_auto_20200112_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='package',
            new_name='name',
        ),
    ]
