# Generated by Django 2.2.9 on 2020-01-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0007_auto_20200112_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='subtitle',
            new_name='package',
        ),
    ]
