# Generated by Django 2.2.9 on 2020-01-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0008_auto_20200112_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='content',
            new_name='image',
        ),
    ]
