# Generated by Django 2.2.9 on 2020-01-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericpage', '0009_auto_20200112_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='image',
            new_name='content',
        ),
    ]
