# Generated by Django 2.2.9 on 2020-01-05 00:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Product Name Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Information About Title', required=True))]))], blank=True, null=True),
        ),
    ]
