# Generated by Django 2.2.9 on 2020-01-05 07:48

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_flexpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='product_image',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Product Name Title', required=True)), ('info', wagtail.core.blocks.TextBlock(help_text='Information About Title', required=True))])), ('card_and_block', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('weight', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('price', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
