# Generated by Django 2.2.9 on 2020-01-06 12:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20200105_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('card_and_block', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('weight', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('price', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
