# Generated by Django 2.2.9 on 2020-01-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_auto_20200106_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Список Tоваров', 'verbose_name_plural': 'Список Tоваров'},
        ),
    ]
