# Generated by Django 2.2.9 on 2020-01-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_auto_20200112_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Список Tоваров', 'verbose_name_plural': 'Tовары'},
        ),
    ]
