# Generated by Django 2.2.9 on 2020-01-14 18:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_auto_20200114_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('card_and_block', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('weight', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('urlpage', wagtail.core.blocks.PageChooserBlock(required=False)), ('price', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
