# Generated by Django 2.2.9 on 2020-01-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_auto_20200114_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='gifurl',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
