# Generated by Django 2.2.9 on 2020-02-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0012_flexpage_gifurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='gifurl',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='photopanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
