# Generated by Django 2.2.9 on 2020-01-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0003_auto_20200103_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='some_link',
            new_name='some_link_cheese',
        ),
        migrations.AddField(
            model_name='homepage',
            name='some_link_meat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
