# Generated by Django 2.2.9 on 2020-01-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContacts',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Контакты , о компании',
                'verbose_name_plural': 'Контакты , о компании',
            },
            bases=('wagtailcore.page',),
        ),
    ]
