# Generated by Django 2.2.9 on 2020-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontacts',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscontacts',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
