# Generated by Django 2.2.9 on 2020-01-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_contacts', '0002_auto_20200112_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
